### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by SunYuQii** [Zhang-xiaokun/BiPNet#1]
您好，请问可以提供数据预处理部分的代码吗？

**Comment by Zhang-xiaokun** [comment]
你好，感谢关注我们的工作。
  数据集预处理代码可以参考我们在SIGIR 2022上的论文 “Price DOES Matter! Modeling Price and Interest Preferences in Session-based Recommendation”
  代码地址 https://github.com/Zhang-xiaokun/CoHHN
  本文的预处理代码与SIGIR上的论文是一样的。
  祝好~
